### ISSUE TITLE
Content Missing

### ISSUE THREAD

**Issue by hspencer** [SemanticMediaWiki/Stragula#36]
I'm working with MediaWiki 1.32.1 and Chameleon 2.0 and, for some reason, using the LocalSettings.php config provided, all body content dissapears:

This is plain Chameleon:
<img width="599" alt="Captura de Pantalla 2019-05-28 a la(s) 20 45 25" src="https://user-images.githubusercontent.com/896632/58521194-b34a3b80-8189-11e9-9025-ce35ab492bc5.png">

and this is after updating LocalSettings.php:
<img width="636" alt="Captura de Pantalla 2019-05-28 a la(s) 20 44 57" src="https://user-images.githubusercontent.com/896632/58521212-c4934800-8189-11e9-9aeb-db597e38f231.png">

I suspect it has something to do with stragula.xml layout schema...

**Comment by ivanhercaz** [comment]
The latest commit that changes [stragula.xml](../stragula.xml) was on 10 Mar 2018, so I don't think the problem was there because it seems to work for another users (me included). And it is strange, I think I test the latest version with the tweaks made by @kghbln, and I remember that it works fine.

If @kghbln knows something it would be very nice, if not I will install MediaWiki with this skin to test that it works... or not.

**Comment by hspencer** [comment]
Wow, that was quick! Thanks!!! 

Just to let you know, I made a fork of Stragula here:  **[bo](https://github.com/hspencer/bo)**. This flavor is implemented here [Amereida](http://www.amereida.cl) and here [Casiopea](http://wiki.ead.pucv.cl). So many thanks for this wonderful work. 
(I'm rebuilding my development environment to make some tweaks but I'm totally puzzled with this bug.)

**Comment by kghbln** [comment]
The issue is that Stragula is Bootstrap 3 and Chameleon 1.7.x only so I am not surprised that it does not work out. I am currently not aware of the changes that come with Bootstrap 4 and Chameleon 2 but this is the way it is.
